zero_optimization:
  stage: 2
  contiguous_gradients: true
  overlap_comm: true
  reduce_scatter: true
  reduce_bucket_size: 5e7
  allgather_bucket_size: 5e7
bf16:
  enabled: true
gradient_accumulation_steps: 16
train_micro_batch_size_per_gpu: 1
steps_per_print: 100
wall_clock_breakdown: false
