"""Shared confidence provenance vocabulary for runtime and evaluation records."""

from enum import Enum


class ConfidenceSource(str, Enum):
    """Origin of a confidence estimate; an origin never certifies a claim's truth."""

    MODEL_SELF_REPORT = "MODEL_SELF_REPORT"
    TOKEN_PROBABILITY = "TOKEN_PROBABILITY"
    HISTORICAL_CALIBRATION = "HISTORICAL_CALIBRATION"
    BEHAVIORAL_EVIDENCE = "BEHAVIORAL_EVIDENCE"
    EXTERNAL_VERIFIER = "EXTERNAL_VERIFIER"
    TOOL_RESULT = "TOOL_RESULT"
    MULTI_EVALUATOR_AGREEMENT = "MULTI_EVALUATOR_AGREEMENT"
    TRAJECTORY_SIGNAL = "TRAJECTORY_SIGNAL"
    INTERNAL_REPRESENTATION = "INTERNAL_REPRESENTATION"
    HUMAN_ADJUDICATION = "HUMAN_ADJUDICATION"
    FUSED = "FUSED"
    LEGACY_UNSPECIFIED = "LEGACY_UNSPECIFIED"
