trainer_type: grpo
model_name: "cpu-demo-model"
dataset_path: "gepa_mindfulness/examples/cpu_demo/prompts.txt"
output_dir: "runs/grpo_cpu_demo"
learning_rate: 1.0e-5
batch_size: 2
gradient_accumulation_steps: 2
max_steps: 10
group_size: 4
kl_coef: 0.05
temperature: 0.8
reward_weights:
  alpha: 0.3
  beta: 0.3
  gamma: 0.2
  delta: 0.2
hallucination:
  confidence_threshold: 0.75
  confident_wrong_penalty: -2.0
  uncertain_wrong_penalty: -0.5
  appropriate_abstention_reward: 0.5
  lazy_abstention_penalty: -0.2
circuit_tracer:
  enabled: true
  trace_frequency: 0.5
  strategy: "sample"
