"""Immutable state and distinct verification-level contracts."""

from .failure_graph import (
    FailureEdge,
    FailureGraph,
    FailureLocalization,
    FailureNode,
    FailureRelation,
    RootCauseStatus,
)
from .interfaces import (
    LocalExecutionVerifier,
    LocalVerificationResult,
    RelationalEvidenceVerifier,
    RelationalVerificationResult,
    VerificationEvidenceBinding,
    VerificationLevel,
    make_local_verification_event,
    make_relational_verification_event,
)
from .runtime_governance import (
    AuthorityGrant,
    AuthorityGrantRegistry,
    AuthorizationDecision,
    AuthorizationReason,
    IrreversibleApprovalBinding,
    RuntimeCapability,
    RuntimeRole,
    TrustedClock,
    action_record_digest,
    authorize_action,
    consume_authorization,
)
from .state import EvidenceClaim, EvidenceState, WorldStateChange

__all__ = [
    "AuthorityGrant",
    "AuthorityGrantRegistry",
    "AuthorizationDecision",
    "AuthorizationReason",
    "EvidenceClaim",
    "EvidenceState",
    "FailureEdge",
    "FailureGraph",
    "FailureLocalization",
    "FailureNode",
    "FailureRelation",
    "LocalExecutionVerifier",
    "LocalVerificationResult",
    "RelationalEvidenceVerifier",
    "RelationalVerificationResult",
    "RootCauseStatus",
    "IrreversibleApprovalBinding",
    "RuntimeCapability",
    "RuntimeRole",
    "TrustedClock",
    "VerificationEvidenceBinding",
    "VerificationLevel",
    "WorldStateChange",
    "action_record_digest",
    "authorize_action",
    "consume_authorization",
    "make_local_verification_event",
    "make_relational_verification_event",
]
