"""Immutable verification, authority, and recovery contracts."""

from .failure_graph import (
    FailureEdge,
    FailureGraph,
    FailureLocalization,
    FailureNode,
    FailureRelation,
    FailureRole,
    FailureRoleEvidence,
    RootCauseStatus,
)
from .interfaces import (
    LocalExecutionVerifier,
    LocalVerificationResult,
    RelationalEvidenceVerifier,
    RelationalVerificationResult,
    VerificationEvidenceBinding,
    VerificationLevel,
    make_local_verification_event,
    make_relational_verification_event,
)
from .recovery import (
    MAX_JSON_SAFE_INTEGER,
    FailureCategory,
    FailureClassificationBinding,
    RecoveryAction,
    RecoveryBudget,
    RecoveryConsumption,
    RecoveryDecision,
    RecoveryStateSnapshot,
    RecoveryStateStore,
    RepeatedRouteFinding,
    consume_recovery,
    select_recovery,
)
from .runtime_governance import (
    ActionAuthorityPolicy,
    AuthorityGrant,
    AuthorityGrantRegistry,
    AuthorizationDecision,
    AuthorizationReason,
    IrreversibleApprovalBinding,
    RuntimeCapability,
    RuntimeRole,
    TrustedClock,
    action_record_digest,
    authorize_action,
    consume_authorization,
)
from .state import ArtifactObservation, EvidenceClaim, EvidenceState, WorldStateChange

__all__ = [
    "AuthorityGrant",
    "ActionAuthorityPolicy",
    "AuthorityGrantRegistry",
    "ArtifactObservation",
    "AuthorizationDecision",
    "AuthorizationReason",
    "EvidenceClaim",
    "EvidenceState",
    "FailureEdge",
    "FailureGraph",
    "FailureLocalization",
    "FailureNode",
    "FailureRelation",
    "FailureRole",
    "FailureRoleEvidence",
    "FailureCategory",
    "FailureClassificationBinding",
    "LocalExecutionVerifier",
    "LocalVerificationResult",
    "RelationalEvidenceVerifier",
    "RelationalVerificationResult",
    "RecoveryAction",
    "RecoveryBudget",
    "RecoveryConsumption",
    "RecoveryDecision",
    "RecoveryStateSnapshot",
    "RecoveryStateStore",
    "RepeatedRouteFinding",
    "RootCauseStatus",
    "IrreversibleApprovalBinding",
    "RuntimeCapability",
    "RuntimeRole",
    "TrustedClock",
    "VerificationEvidenceBinding",
    "VerificationLevel",
    "WorldStateChange",
    "MAX_JSON_SAFE_INTEGER",
    "action_record_digest",
    "authorize_action",
    "consume_authorization",
    "consume_recovery",
    "make_local_verification_event",
    "make_relational_verification_event",
    "select_recovery",
]
