model_name: "comparison-model"
dataset_path: "gepa_datasets/ethical_qa.jsonl"
output_dir: "runs/comparison"
learning_rate: 1.0e-5
batch_size: 4
gradient_accumulation_steps: 2
max_steps: 100
reward_weights:
  alpha: 0.3
  beta: 0.3
  gamma: 0.2
  delta: 0.2
hallucination:
  confidence_threshold: 0.75
  confident_wrong_penalty: -2.0
  uncertain_wrong_penalty: -0.5
  appropriate_abstention_reward: 0.5
  lazy_abstention_penalty: -0.2
circuit_tracer:
  enabled: true
  trace_frequency: 0.5
  strategy: "mixed"
